

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "EntityFramework.Reverse.POCO.Generator\App.config"
//     Connection String Name: "MyDbContextSqlCE4"
//     Connection String:      "Data Source=C:\source\EntityFramework-Reverse-POCO-Code-First-Generator\EntityFramework.Reverse.POCO.Generator\App_Data\NorthwindSqlCe40.sdf"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to load provider "System.Data.SqlServerCe.4.0".
// -----------------------------------------------------------------------------------------
Unable to find the requested .Net Framework Data Provider.  It may not be installed.
System.ArgumentException
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at Microsoft.VisualStudio.TextTemplating84FC6388309F6882C4F22362253CB348B1B56D76BD995C6663F21CE1AE651B9AC4BB2A33531F554ECCA4C66DD5B36F2E10BA034E9F9AE464F5F7C0D1C9CC859D.GeneratedTextTransformation.GetDbProviderFactory() in C:\source\EntityFramework-Reverse-POCO-Code-First-Generator\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.Core.ttinclude:line 679



